/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EtherlockFactoryContract } from "./EtherlockFactoryContract";
export type { MyContract } from "./MyContract";
