/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSubscriberSol from "./ISubscriber.sol";
export type { iSubscriberSol };
import type * as subscriberSol from "./Subscriber.sol";
export type { subscriberSol };
