/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as etherlockNft from "./EtherlockNft";
export type { etherlockNft };
import type * as fabric from "./Fabric";
export type { fabric };
import type * as subs from "./Subs";
export type { subs };
