/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fabricNftSol from "./FabricNFT.sol";
export type { fabricNftSol };
import type * as fabricTokenSol from "./FabricToken.sol";
export type { fabricTokenSol };
