/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyContract__factory } from "./MyContract__factory";
export { MyContractFactory__factory } from "./MyContractFactory__factory";
